[server]
<<<<<<< HEAD
<<<<<<< HEAD
headless = true
address = "0.0.0.0"
port = 5000
=======
<<<<<<< HEAD
=======
>>>>>>> origin/replit-agent
<<<<<<< HEAD
headless = true
address = "0.0.0.0"
port = 5000
=======
maxUploadSize = 10000
maxMessageSize = 10000
headless = true
enableCORS = false

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
>>>>>>> d9a3dfcdf70c971baab32a146dc15b622ed329ee
=======
headless = true
address = "0.0.0.0"
port = 5000
>>>>>>> b49860d (Create a collaborative workspace for app ideas and requirements)
<<<<<<< HEAD
>>>>>>> origin/replit-agent
=======
>>>>>>> origin/replit-agent
